[package]
name = "nuts-py"
version = "0.1.0"
authors = ["Adrian Seyboldt <adrian.seyboldt@gmail.com>"]
edition = "2021"

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]

[lib]
name = "nuts_py"
crate-type = ["cdylib"]
#features = ["extension-module"]

[dependencies]
nuts-rs = { path = "../nuts-rs" }
#tvm = { path = "../tvm/rust/tvm" }
numpy = "0.16.2"
ndarray = "0.15.4"
rand = "0.8.5"
crossbeam = "0.8.1"
thiserror = "1.0.31"

[dependencies.pyo3]
version = "0.16.5"
features = ["extension-module", "auto-initialize"]

[dev-dependencies]
criterion = "0.3.5"

[profile.release]
#panic = "abort"
debug = 2
lto = "fat"
codegen-units = 1
opt-level = 2

[profile.bench]
debug = true
lto = "fat"

#[[bench]]
#name = "run_tvm_leapfrog"
#harness = false
