[package]
name = "nutpie"
version = "0.5.1"
authors = ["Adrian Seyboldt <adrian.seyboldt@gmail.com>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/pymc-devs/nutpie"
keywords = ["statistics", "bayes"]
description = "Python wrapper for nuts-rs -- a NUTS sampler written in Rust."

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]
simd_support = ["nuts-rs/simd_support"]

[lib]
name = "nutpie"
crate-type = ["cdylib"]

[dependencies]
nuts-rs = "0.4.1"
numpy = "0.18.0"
ndarray = "0.15.6"
rand = "0.8.5"
crossbeam = "0.8.2"
thiserror = "1.0.40"
threadpool = "1.8.1"
rand_chacha = "0.3.1"
rayon = "1.7.0"
arrow2 = "0.17.0"
anyhow = "1.0.70"
itertools = "0.10.5"

[dependencies.bridgestan]
version = "1.0.2"
path = "../bridgestan/rust/"

[dependencies.pyo3]
version = "0.18.2"
features = ["extension-module", "auto-initialize", "anyhow"]

[dev-dependencies]
criterion = "0.4.0"

[profile.release]
debug = true
lto = "fat"
codegen-units = 1
opt-level = 2

[profile.bench]
debug = true
lto = "fat"
