[package]
name = "nuts-py"
version = "0.1.0"
authors = ["Adrian Seyboldt <adrian.seyboldt@gmail.com>"]
edition = "2018"

[lib]
name = "nuts_py"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.12.3"
features = ["extension-module"]

[dependencies]
nuts-rs = { path = "../nuts-rs" }
numpy = "0.12"
ndarray = "0.13"
rand = "0.7"

[profile.release]
panic = "abort"
debug = true
lto = "fat"
